### ISSUE TITLE
Property 'textLabel' not found on object of type 'RNSnackBarView *';

### ISSUE THREAD

**Issue by hetansh-Tatvasoft** [cooperka/react-native-snackbar#200]
Using package version - 2.7.0, 
RN- 0.71.6

getting below issue while building for iOS

error message:- _

1. Property 'textLabel' not found on object of type 'RNSnackBarView *'; did you mean to access instance variable 'textLabel'?
2. _Property 'actionButton' not found on object of type 'RNSnackBarView *'; did you mean to access instance variable 'actionButton'?

![Screenshot 2023-05-10 at 4 39 20 PM](https://github.com/cooperka/react-native-snackbar/assets/85100474/085c88dc-4460-4d86-9536-900785b537e6)

replacing 

`self.textLabel.alpha` with `textLabel.alpha` solves the issue and built successfully
similarly for the replaced `self.actionButton.alpha` with `actionButton.alpha`.

**Comment by tyler-coleman** [comment]
Oof

**Comment by hansa0712004212** [comment]
I'm getting the same error for iOS

**Comment by cooperka** [comment]
i believe this broke in v2.7.0; i've just published v2.7.1 with a fix that should hopefully resolve this. please upgrade and let me know.

edit: i had originally also published a fix in v2.6.1, but that is now reverted in v2.6.2 because that release was unaffected.

**Comment by jbagaresgaray** [comment]
@cooperka Issue still happening on Expo 48 using react-native-snackbar@2.7.1

![image](https://github.com/cooperka/react-native-snackbar/assets/3625802/b82fee1a-b2b0-46aa-8228-e247dee3defc)


![image](https://github.com/cooperka/react-native-snackbar/assets/3625802/7d4a3892-a1ec-4233-a2ae-a4c4b22bc4e7)

**Comment by cooperka** [comment]
thanks for the screenshot @jbagaresgaray, I welcome a pull request if you can figure out what's causing the error.
